<?xml version="1.0" encoding="UTF-8" ?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:schema="http://projectCobart/namespace/scheme"
                  xmlns:tns="http://projectCobart/namespace/definitions"
                  targetNamespace="http://projectCobart/namespace/definitions">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://projectCobart/namespace/scheme" schemaLocation="../scheme/dataContract.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="MovieRequest">
        <wsdl:part element="schema:MovieRequest" name="MovieParam"/>
    </wsdl:message>

    <wsdl:message name="SallesListResponse">
        <wsdl:part element="schema:SallesListResponse" name="SalleListResult"/>
    </wsdl:message>


    <wsdl:portType name="Cobar">

        <wsdl:operation name="GetListSalles">
            <wsdl:input message="tns:MovieRequest"/>
            <wsdl:output message="tns:SallesListResponse"/>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="CobarBinding" type="tns:Cobar">

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="GetListSalles">

            <soap:operation soapAction=""/>
            <wsdl:input name="SalleListRequest">
                <soap:body use="literal"/>
            </wsdl:input>

            <wsdl:output name="SalleListResponse">
                <soap:body use="literal"/>
            </wsdl:output>

        </wsdl:operation>

    </wsdl:binding>
    
    <wsdl:service name="CobarService">
        <wsdl:port name="CobarPort" binding="CobarBinding">
            <soap:address location="localhost:8080/Cobar"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
