<?xml version="1.0" encoding="UTF-8" ?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:schema="http://projectCobart/namespace"
                  xmlns:tns="Mynamespace"
                  targetNamespace="Mynamespace">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://projectCobart/namespace" schemaLocation="../scheme/dataContract.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="theatreListRequest">
        <wsdl:part element="schema:Movie" name="MovieParam"/>
    </wsdl:message>

    <wsdl:message name="theatreListResponse">
        <wsdl:part element="schema:TheatreList" name="TheatreListResult"/>
    </wsdl:message>


    <wsdl:portType name="TheatreSearch">

        <wsdl:operation name="GetListTheatre">
            <wsdl:input message="tns:theatreListRequest"/>
            <wsdl:output message="tns:theatreListResponse"/>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="TheatreSearchPortBinding" type="tns:TheatreSearch">

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="GetListTheatre">

            <soap:operation soapAction=""/>
            <wsdl:input name="MovieTheatreListRequest">
                <soap:body use="literal"/>
            </wsdl:input>

            <wsdl:output name="MovieTheatreListResponse">
                <soap:body use="literal"/>
            </wsdl:output>

        </wsdl:operation>

    </wsdl:binding>
    
    <wsdl:service name="SearchService">
        <wsdl:port name="SearchPort" binding="TheatreSearchPortBinding">
            <soap:address location="http://localhost:8080/SearchService"/>
        </wsdl:port>
    </wsdl:service>



</wsdl:definitions>
