<?xml version="1.0" encoding="UTF-8" ?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:schema="http://projectCobart/namespace"
                  xmlns:tns="Mynamespace"
                  targetNamespace="Mynamespace">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://projectCobart/namespace" schemaLocation="../scheme/dataContract.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="SalleListRequest">
        <wsdl:part element="schema:Movie" name="MovieParam"/>
    </wsdl:message>

    <wsdl:message name="SalleListResponse">
        <wsdl:part element="schema:SallesList" name="SalleListResult"/>
    </wsdl:message>


    <wsdl:portType name="SalleListSearch">

        <wsdl:operation name="GetListSalles">
            <wsdl:input message="tns:SalleListRequest"/>
            <wsdl:output message="tns:SalleListResponse"/>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="SalleListSearchPortBinding" type="tns:SalleListSearch">

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="GetListSalles">

            <soap:operation soapAction=""/>
            <wsdl:input name="SalleListRequest">
                <soap:body use="literal"/>
            </wsdl:input>

            <wsdl:output name="SalleListResponse">
                <soap:body use="literal"/>
            </wsdl:output>

        </wsdl:operation>

    </wsdl:binding>
    
    <wsdl:service name="SearchService">
        <wsdl:port name="SearchPort" binding="SalleListSearchPortBinding">
            <soap:address location="localhost:8080/mywebapp/SearchService"/>
        </wsdl:port>
    </wsdl:service>



</wsdl:definitions>
